// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWT29DuYw92EhjQ2YVDKX_1V6eBrHW_pM',
    appId: '1:424178962169:web:33cbc3a3e43eb4c49f1c28',
    messagingSenderId: '424178962169',
    projectId: 'tocha-49ef1',
    authDomain: 'tocha-49ef1.firebaseapp.com',
    storageBucket: 'tocha-49ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcYCeCaq_DnZBJOP_wmwqgQzAI8xmcvak',
    appId: '1:424178962169:ios:2bed85b22918907f9f1c28',
    messagingSenderId: '424178962169',
    projectId: 'tocha-49ef1',
    storageBucket: 'tocha-49ef1.appspot.com',
    androidClientId: '424178962169-1lcg6o39mrb1pnt8m875lt61od1ckpgb.apps.googleusercontent.com',
    iosClientId: '424178962169-2bdqf6n23agu33ui5ono4c1ge9llro9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tocha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcYCeCaq_DnZBJOP_wmwqgQzAI8xmcvak',
    appId: '1:424178962169:ios:2bed85b22918907f9f1c28',
    messagingSenderId: '424178962169',
    projectId: 'tocha-49ef1',
    storageBucket: 'tocha-49ef1.appspot.com',
    androidClientId: '424178962169-1lcg6o39mrb1pnt8m875lt61od1ckpgb.apps.googleusercontent.com',
    iosClientId: '424178962169-2bdqf6n23agu33ui5ono4c1ge9llro9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tocha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWT29DuYw92EhjQ2YVDKX_1V6eBrHW_pM',
    appId: '1:424178962169:web:5d78207e72f32ecf9f1c28',
    messagingSenderId: '424178962169',
    projectId: 'tocha-49ef1',
    authDomain: 'tocha-49ef1.firebaseapp.com',
    storageBucket: 'tocha-49ef1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNzIgrEjQVi2AaZY0F5nXbU5aEfF20J4',
    appId: '1:424178962169:android:0c548adffe7a0fe89f1c28',
    messagingSenderId: '424178962169',
    projectId: 'tocha-49ef1',
    storageBucket: 'tocha-49ef1.appspot.com',
  );

}